import { CalendarDays, Clock3, MapPin, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { activityApi, getOrCreateTrip } from '../../api/travelWiseApi'
import { useAuth } from '../../context/AuthContext'
import ActivityForm from './ActivityForm'

const initialEvents = [{ day: '12', month: 'SEP', title: 'Arrive in Colombo', location: 'Bandaranaike International Airport', time: '14:30 - 16:00', type: 'Travel' }, { day: '14', month: 'SEP', title: 'Galle Fort walking tour', location: 'Galle Fort', time: '09:00 - 12:00', type: 'Experience' }, { day: '16', month: 'SEP', title: 'Slow afternoon by the sea', location: 'Unawatuna Beach', time: '15:00 - 18:00', type: 'Leisure' }]
function toEvent(activity) { const start = new Date(activity.startTime); const end = new Date(activity.endTime); return { id: activity.id, day: String(start.getDate()).padStart(2, '0'), month: start.toLocaleString('en', { month: 'short' }).toUpperCase(), title: activity.title, location: activity.location, time: `${start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} - ${end.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`, type: activity.interestType || 'Activity' } }

export default function ActivityPage() { const { user } = useAuth(); const [events, setEvents] = useState(initialEvents); const [selectedTrip, setSelectedTrip] = useState(null); const [showForm, setShowForm] = useState(false); const [serverError, setServerError] = useState(''); useEffect(() => { if (user?.id) getOrCreateTrip(user.id).then(setSelectedTrip).catch((error) => setServerError(error.response?.data || 'Could not load the selected trip.')) }, [user?.id]); async function submit(values) { const trip = selectedTrip || await getOrCreateTrip(user.id); const { data } = await activityApi.addActivity({ ...values, tripId: trip.id }); setEvents((current) => [...current, toEvent(data)]); setSelectedTrip(trip); setShowForm(false) } async function removeActivity(event) { if (!event.id || !window.confirm('Delete this activity?')) return; try { await activityApi.remove(event.id); setEvents((current) => current.filter((item) => item.id !== event.id)) } catch (error) { setServerError(error.response?.data || 'Could not delete this activity.') } } return <><div className="page-intro"><div><span className="eyebrow">Your itinerary</span><h1>Make time for wonder.</h1><p>A clear view of the days ahead, with space for spontaneity.</p></div><button className="button button-coral" onClick={() => setShowForm(!showForm)}><Plus size={16} /> Schedule activity</button></div>{serverError && <div className="form-error">{String(serverError)}</div>}{showForm && <ActivityForm selectedTrip={selectedTrip} onSubmit={submit} onCancel={() => setShowForm(false)} />}<section className="calendar-panel"><div className="calendar-toolbar"><button className="icon-button">‹</button><strong>September 2026</strong><button className="icon-button">›</button><span className="calendar-view"><CalendarDays size={15} /> Agenda view</span></div><div className="agenda">{events.map((event, index) => <article className="agenda-item" key={`${event.title}-${index}`}><div className="date-block"><strong>{event.day}</strong><span>{event.month}</span></div><div className="agenda-line" /><div className="agenda-copy"><span className="eyebrow">{event.type}</span><h2>{event.title}</h2><p><MapPin size={14} /> {event.location} <Clock3 size={14} /> {event.time}</p></div>{event.id && <button className="icon-button" title="Delete activity" onClick={() => removeActivity(event)}><Trash2 size={14} /></button>}</article>)}</div></section></> }
