import { ArrowUpRight, CheckCircle2, ShieldAlert, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { z } from 'zod'
import { getOrCreateTrip, riskApi } from '../../api/travelWiseApi'
import { useAuth } from '../../context/AuthContext'
import LocationField from '../../components/LocationField'
import '../../components/location-fields.css'
export const riskSchema = z.object({ destination: z.string().min(2), severityLevel: z.enum(['Low', 'Moderate', 'High', 'Critical']), advisoryMessage: z.string().min(2) })
const initialRisks = [{ destination: 'Sri Lanka · Weather', level: 'Low', message: 'Dry season conditions expected across your route.', updated: 'Updated 2h ago' }, { destination: 'Sri Lanka · Health', level: 'Moderate', message: 'Stay hydrated and carry mosquito repellent for the south coast.', updated: 'Updated yesterday' }, { destination: 'Sri Lanka · Local advisories', level: 'Low', message: 'No active travel restrictions for your destinations.', updated: 'Updated Sep 19' }]
export default function RiskPage() { const { user } = useAuth(); const [items, setItems] = useState(initialRisks); const [destination, setDestination] = useState('Sri Lanka'); const [serverError, setServerError] = useState(''); async function refresh() { setServerError(''); try { const trip = await getOrCreateTrip(user.id); const { data } = await riskApi.addAssessment({ tripId: trip.id, destination, severityLevel: 'Low', advisoryMessage: 'No active travel restrictions.' }); setItems((current) => [{ id: data.id, destination: `${data.destination} · Latest assessment`, level: data.severityLevel, message: data.advisoryMessage, updated: 'Just now' }, ...current]) } catch (error) { setServerError(error.response?.data || 'Could not refresh travel intelligence.') } } async function removeAssessment(item) { if (!item.id || !window.confirm('Delete this assessment?')) return; try { await riskApi.remove(item.id); setItems((current) => current.filter((entry) => entry.id !== item.id)) } catch (error) { setServerError(error.response?.data || 'Could not delete this assessment.') } } return <><div className="page-intro"><div><span className="eyebrow">Travel intelligence</span><h1>Know before you go.</h1><p>Helpful signals, clearly surfaced. No doom scrolling required.</p></div><button className="button button-dark" onClick={refresh}><ShieldAlert size={16} /> Refresh radar</button></div><div className="risk-location"><span className="eyebrow">Assess a destination</span><LocationField label="Risk destination" value={destination} onChange={setDestination} placeholder="Search Google Maps" /></div>{serverError && <div className="form-error">{String(serverError)}</div>}<div className="risk-hero"><div className="risk-score"><span>Overall outlook</span><strong>Good to go</strong><div className="risk-meter"><span /></div><small>Based on {items.length} active signals</small></div><div className="risk-hero-note"><CheckCircle2 size={20} /><span><strong>No critical alerts</strong>Your current itinerary is in a comfortable zone.</span></div></div><section className="risk-list">{items.map((item, index) => <article className="risk-card" key={`${item.destination}-${index}`}><div className={`severity-badge ${item.level.toLowerCase()}`}><span />{item.level}</div><div className="risk-card-copy"><h2>{item.destination}</h2><p>{item.message}</p><small>{item.updated}</small></div>{item.id ? <button className="icon-button" title="Delete assessment" onClick={() => removeAssessment(item)}><Trash2 size={14} /></button> : <ArrowUpRight size={18} />}</article>)}</section></> }
