import { ArrowUpRight, CheckCircle2, ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import { z } from 'zod'
import { riskApi } from '../../api/travelWiseApi'

const riskSchema = z.object({ destination: z.string().min(2), severityLevel: z.string().min(1), advisoryMessage: z.string().min(2) })
const initialRisks = [{ destination: 'Sri Lanka · Weather', level: 'Low', message: 'Dry season conditions expected across your route.', updated: 'Updated 2h ago' }, { destination: 'Sri Lanka · Health', level: 'Moderate', message: 'Stay hydrated and carry mosquito repellent for the south coast.', updated: 'Updated yesterday' }, { destination: 'Sri Lanka · Local advisories', level: 'Low', message: 'No active travel restrictions for your destinations.', updated: 'Updated Sep 19' }]

export default function RiskPage() { const [items, setItems] = useState(initialRisks); const [serverError, setServerError] = useState(''); async function refresh() { setServerError(''); try { const { data } = await riskApi.addAssessment({ tripId: 1, destination: 'Sri Lanka', severityLevel: 'Low', advisoryMessage: 'No active travel restrictions.' }); setItems((current) => [{ destination: `${data.destination} · Latest assessment`, level: data.severityLevel, message: data.advisoryMessage, updated: 'Just now' }, ...current]) } catch (error) { setServerError(error.response?.data || 'Could not refresh travel intelligence.') } } return <><div className="page-intro"><div><span className="eyebrow">Travel intelligence</span><h1>Know before you go.</h1><p>Helpful signals, clearly surfaced. No doom scrolling required.</p></div><button className="button button-dark" onClick={refresh}><ShieldAlert size={16} /> Refresh radar</button></div>{serverError && <div className="form-error">{String(serverError)}</div>}<div className="risk-hero"><div className="risk-score"><span>Overall outlook</span><strong>Good to go</strong><div className="risk-meter"><span /></div><small>Based on {items.length} active signals</small></div><div className="risk-hero-note"><CheckCircle2 size={20} /><span><strong>No critical alerts</strong>Your current itinerary is in a comfortable zone.</span></div></div><section className="risk-list">{items.map((item, index) => <article className="risk-card" key={`${item.destination}-${index}`}><div className={`severity-badge ${item.level.toLowerCase()}`}><span />{item.level}</div><div className="risk-card-copy"><h2>{item.destination}</h2><p>{item.message}</p><small>{item.updated}</small></div><ArrowUpRight size={18} /></article>)}</section></> }
export { riskSchema }
