import { ArrowUpRight, MapPin, Star } from 'lucide-react'
import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import GoogleMapPanel from './GoogleMapPanel'
import '../../../components/location-fields.css'
import './search-results-clean.css'

const results = [{ id: 1, name: 'The Galle Fort Edit', place: 'Galle Fort, Galle, Sri Lanka', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=85', rating: '4.9', tags: ['Culture', 'Coastal'], price: '$420' }, { id: 2, name: 'Tea Country Slow Days', place: 'Nuwara Eliya, Sri Lanka', image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=700&q=85', rating: '4.8', tags: ['Nature', 'Wellness'], price: '$680' }, { id: 3, name: 'Wild Coast Weekender', place: 'Yala National Park, Sri Lanka', image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=700&q=85', rating: '4.7', tags: ['Wildlife', 'Adventure'], price: '$510' }]

export default function SearchResults() { const [selected, setSelected] = useState(1); const [params] = useSearchParams(); const destination = params.get('destination') || 'Sri Lanka'; const selectedPlace = results.find((item) => item.id === selected)?.place || destination; return <section className="section results-section" id="explore"><div className="section-heading"><div><span className="eyebrow">{params.get('domain') || 'Curated for you'} · {destination}</span><h2>Start with a feeling.</h2></div><a href="#plans" className="arrow-link">See all journeys <ArrowUpRight size={16} /></a></div><div className="results-grid"><div className="result-list">{results.map((item) => <article className={`result-card ${selected === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelected(item.id)}><img src={item.image} alt={item.name} /><div className="result-copy"><div className="result-meta"><span><MapPin size={13} /> {item.place}</span><span><Star size={13} fill="currentColor" /> {item.rating}</span></div><h3>{item.name}</h3><div className="tag-row">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="result-bottom"><strong>from {item.price}</strong><button className="mini-button" type="button">View details <ArrowUpRight size={14} /></button></div></div></article>)}</div><div className="map-placeholder"><GoogleMapPanel destination={selectedPlace} /></div></div></section> }
