import { Plus, Wallet } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import axiosInstance from '../../api/axiosInstance'
const budgetSchema = z.object({ category: z.string().min(1, 'Choose a category'), description: z.string().min(2, 'Add a short description'), amount: z.coerce.number().positive('Amount must be greater than 0'), expenseDate: z.string().min(1, 'Select a date') })
const expenses = [{ category: 'Stay', description: 'The Fort Bazaar · 3 nights', date: 'Sep 12', amount: '$420' }, { category: 'Transport', description: 'Airport transfer', date: 'Sep 12', amount: '$36' }, { category: 'Experience', description: 'Galle Fort walking tour', date: 'Sep 14', amount: '$82' }, { category: 'Food', description: 'Dinner at The Tuna & The Crab', date: 'Sep 15', amount: '$64' }]
export default function BudgetPage() { const [rows, setRows] = useState(expenses); const [showForm, setShowForm] = useState(false); const { register, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(budgetSchema) }); async function submit(values) { try { await axiosInstance.post('/Budget/expenses', { ...values, budgetId: 1, amount: Number(values.amount) }); } catch { /* Demo mode keeps the optimistic row visible. */ } setRows([{ ...values, date: values.expenseDate, amount: `$${Number(values.amount).toFixed(2)}` }, ...rows]); reset(); setShowForm(false) } return <><div className="page-intro"><div><span className="eyebrow">Trip finances</span><h1>Budget, beautifully clear.</h1><p>Keep the numbers in view without letting them take over.</p></div><button className="button button-coral" onClick={() => setShowForm(!showForm)}><Plus size={16} /> Add expense</button></div><div className="feature-summary"><div className="summary-icon"><Wallet size={20} /></div><div><span>Total allocated</span><strong>$2,400</strong></div><div><span>Spent to date</span><strong>$1,860</strong></div><div><span>Remaining</span><strong className="positive">$540</strong></div></div>{showForm && <form className="inline-form" onSubmit={handleSubmit(submit)}><label>Category<select {...register('category')}><option value="">Select</option><option>Stay</option><option>Transport</option><option>Experience</option><option>Food</option></select>{errors.category && <small className="field-error">{errors.category.message}</small>}</label><label>Description<input {...register('description')} placeholder="What was this for?" />{errors.description && <small className="field-error">{errors.description.message}</small>}</label><label>Amount<input type="number" step="0.01" {...register('amount')} placeholder="0.00" />{errors.amount && <small className="field-error">{errors.amount.message}</small>}</label><label>Date<input type="date" {...register('expenseDate')} />{errors.expenseDate && <small className="field-error">{errors.expenseDate.message}</small>}</label><button className="button button-dark" type="submit">Save</button></form>}<section className="table-panel"><div className="table-heading"><h2>Recent expenses</h2><span>{rows.length} items</span></div><div className="data-table"><div className="table-row table-header"><span>Category</span><span>Description</span><span>Date</span><span>Amount</span></div>{rows.map((row, i) => <div className="table-row" key={`${row.description}-${i}`}><span><b className="category-dot" />{row.category}</span><span>{row.description}</span><span>{row.date}</span><strong>{row.amount}</strong></div>)}</div></section></> }
