import { CheckCircle2, FileCheck2, FileText, Plus, UploadCloud } from 'lucide-react'
import { useState } from 'react'
import { z } from 'zod'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import axiosInstance from '../../api/axiosInstance'
const readinessSchema = z.object({ documentType: z.string().min(1, 'Choose a document'), documentNumber: z.string().min(3, 'Add the document number'), expiryDate: z.string().refine((date) => new Date(date) > new Date(), 'Expiration date must be in the future') })
const docs = [{ name: 'Passport', number: '•••• 2941', expiry: 'Expires Dec 2028', ready: true }, { name: 'Travel insurance', number: 'Policy · TW-8842', expiry: 'Expires Sep 2026', ready: true }, { name: 'International driving permit', number: 'Not added', expiry: 'Optional for your trip', ready: false }]
export default function ReadinessPage() { const [showForm, setShowForm] = useState(false); const [documents, setDocuments] = useState(docs); const { register, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(readinessSchema) }); async function submit(values) { try { await axiosInstance.post('/Readiness', { ...values, tripId: 1 }) } catch { /* Keep the local preview usable without a running API. */ } setDocuments([{ name: values.documentType, number: `•••• ${values.documentNumber.slice(-4)}`, expiry: `Expires ${values.expiryDate}`, ready: true }, ...documents]); reset(); setShowForm(false) } return <><div className="page-intro"><div><span className="eyebrow">Trip readiness</span><h1>Ready when you are.</h1><p>Keep the important documents close, current, and quietly checked off.</p></div><button className="button button-coral" onClick={() => setShowForm(!showForm)}><Plus size={16} /> Add document</button></div><div className="readiness-score"><div className="score-ring"><strong>92</strong><span>/100</span></div><div><span className="eyebrow">Your readiness score</span><h2>Looking very good.</h2><p>One optional document left to make this trip feel effortless.</p></div><FileCheck2 size={34} /></div>{showForm && <form className="inline-form" onSubmit={handleSubmit(submit)}><label>Document type<select {...register('documentType')}><option value="">Select</option><option>Passport</option><option>Travel insurance</option><option>Driving permit</option></select>{errors.documentType && <small className="field-error">{errors.documentType.message}</small>}</label><label>Document number<input {...register('documentNumber')} placeholder="Document number" />{errors.documentNumber && <small className="field-error">{errors.documentNumber.message}</small>}</label><label>Expiration date<input type="date" {...register('expiryDate')} />{errors.expiryDate && <small className="field-error">{errors.expiryDate.message}</small>}</label><button className="button button-dark" type="submit">Save</button></form>}<section className="document-list">{documents.map((doc) => <article className="document-card" key={doc.name}><div className="document-icon"><FileText size={20} /></div><div><h2>{doc.name}</h2><p>{doc.number}</p><small>{doc.expiry}</small></div><span className={doc.ready ? 'document-ready' : 'document-optional'}>{doc.ready ? <><CheckCircle2 size={15} /> Verified</> : <><UploadCloud size={15} /> Add document</>}</span></article>)}</section></> }
export { readinessSchema }
